services:
  ui:
    container_name: app_ui
    build: ./develop/src/main/frontend/
    volumes:
      - ./develop/src/main/frontend/src:/app/src
    ports:
      - 3000:3000

  api:
    container_name: app_api
    build: ./
    environment:
      # note that "postgres" has to match the name of the postgres container
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/vestana"
      SPRING_DATASOURCE_USERNAME: postgre
      SPRING_DATASOURCE_PASSWORD: pswd
      SPRING_LOGGING_LEVEL_ROOT: INFO
      SPRING_SERVER_PORT: 8080
    ports:
      - 8080:8080

  postgres:
    container_name: app_postgres
    image: postgres:13-alpine
    restart: always
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: pswd
      POSTGRES_DB: vestana
    ports:
      - 5432:5432